### ISSUE TITLE
Add instructions for Windows in README

### ISSUE THREAD

**Issue by jwokaty** [waldronlab/curatedMetagenomicDataTerminal#10]
Quoting @cmirzayi "shebangs don't work so you have to add R to your Windows path then run like R curatedMetagenomicData or Rscript curatedMetagenomicData depending on how you setup your path."

**Comment by schifferl** [comment]
The documentation is sufficient at the moment. If you (@jwokaty) or @cmirzayi wants to submit a pull request with instructions on how to use the software with Windows, I'll merge it but I am going to close the issue for now.

**Comment by lwaldron** [comment]
@schifferl the below is the only documentation I'm currently aware of, which hardly seems like a closed issue - am I missing some other documentation elsewhere? Closing the issue means no additional documentation is sought. If this is the only source of Windows documentation, @cmirzayi would you create a PR on README.md?

> Do you have Windows and want to use curatedMetagenomicDataTerminal? It won’t work for you at the moment, but if you insist, and are willing to accept the duty of testing, we can work together to make it possible. Get in touch and we’ll discuss.

**Comment by cmirzayi** [comment]
This is almost ready. I'm stuck making a symbolic link (the equivalent of `ln fs`) in Windows, but I'm figuring it out. I will likely have to update the install.R file to provide Windows-specific code. I'll have a pull request with a working version for Windows by the end of today.

**Comment by schifferl** [comment]
@lwaldron, the documentation is correct at the moment because Windows is not supported yet and that much is stated. I don't see the sense in having an open issue for something that is not broken. Essentially, there is no issue with the documentation as it stands. If this were a feature request, we could discuss that – but it's not one I have bandwidth to implement at the moment. So, if it comes as a pull request I will gladly merge it, but the issue should remain closed.

**Comment by lwaldron** [comment]
@cmirzayi  you don't need a symbolic link though, do you? You could also just copy the executable onto somewhere on your $PATH, or add its directory to your $PATH...

@schifferl I guess we can agree to disagree: Windows _is_ already supported provided some additional documentation, as @cmirzayi has found, but the documentation doesn't reflect those instructions. Thus a documentation issue seems quite appropriate to me, but I'll leave it closed.

**Comment by cmirzayi** [comment]
Oh yeah I suppose I was trying to mimic what it was already doing as much as possible. I'll see if I can write something where it just copies the file.
